# Generated by Django 4.0.5 on 2022-09-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='description',
        ),
    ]
